[WIP] [Checkstyle] Provide Sider's recommended set of rules
sider/runners pull request #1619
Opened 2020-11-04 07:02 UTC by sleeeto

Fix #1618 

> Check the following items.

- [ ] Add a new [changelog](https://github.com/sider/runners/blob/master/CHANGELOG.md) entry if this change is notable.

If you are adding a new runner:

- [ ] Read and follow the [document](https://github.com/sider/runners/blob/master/docs/how-to-write-a-new-runner.md) for a new runner
- [ ] Add a new tool to [`analyzers.yml`](https://github.com/sider/runners/blob/master/analyzers.yml).
- [ ] Run `bundle exec rake readme:generate` and commit the updated `README.md`.
- [ ] Add a new tool to the [Dependabot configuration](https://github.com/sider/runners/blob/master/.github/dependabot.yml) if needed.
- [ ] Provide option(s) that users can customize.
- [ ] Write smoke test cases. E.g. all options, successful end, warnings, errors, etc.
- [ ] Add a [CI setting](https://github.com/sider/runners/blob/master/.github/workflows/build.yml).
- [ ] Write a [document](https://github.com/sider/sider-docs) and link the pull request, e.g. `sider/sider-docs#789`

2020-11-11 05:22 UTC, ybiquitous commented
See also #1611

2020-11-12 07:59 UTC, sleeeto commented
I have a questions.
- This PR is showing only the announcement of default-checkstyle rules. Do I need add a new changelog entry ?

2020-11-12 08:59 UTC, yykamei commented
> I have a questions.
> 
> * This PR is showing only the announcement of default-checkstyle rules. Do I need add a new changelog entry ?

Yes, I think so. #1505 added a changelog as well.

2020-11-16 01:34 UTC, suetsuguk commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +<?xml version="1.0"?>
Please comment out rules to be excluded from our default set of rules.
I am still reviewing the analysis results, but it's ok to apply them as of now.

2020-11-16 03:24 UTC, suetsuguk reviewed
Please consider the comments bellow.

2020-11-16 12:22 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +<?xml version="1.0"?>
I changed the default set of rules to "google", which is current default.

2020-11-16 12:22 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +        #  trace_writer.message "The `config` option in `#{config_linter[:config]}` is specified. The Sider's recommended ruleset is ignored."
fixed

2020-11-16 12:22 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +      if config_linter[:config]
fixed.

2020-11-16 12:23 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +        original_recommended_file_path(CONFIG_FILE_NAME)
fixed.

2020-11-16 12:23 UTC, sleeeto commented on lib/runners/recommended_config.rb
> +    end
fixed.

2020-11-16 12:25 UTC, sleeeto commented on test/smokes/checkstyle/default_rules/src/Hello.java
> +package sample.checkstyle;
I add a new smoke test, "default_rules" whichi is current default set of rules.

2020-11-16 12:25 UTC, sleeeto commented on test/smokes/checkstyle/expectations.rb
> +  warnings: :_,
fixed.

2020-11-16 12:26 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +      <!-- suppresion is required till https://github.com/checkstyle/checkstyle/issues/7541 -->
> __[Misspell]__ "suppresion" is a misspelling of "suppression" ([view](https://sider.review/gh/repos/202486306/pulls/1619#issue-5179418))
>
> <details>
>
> | Rule | Correct | Incorrect |
> | ---- | ------- | --------- |
> | `suppression` | suppression | suppresion |
>
> You can [close this issue](https://sider.review/gh/repos/202486306/pulls/1619#issue-5179418) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

This is default set of rules.

2020-11-17 04:25 UTC, suetsuguk commented on CHANGELOG.md
> +- Checkstyle Provide Sider's recommended ruleset [#1505](https://github.com/sider/runners/pull/1619)
```suggestion
- **Checkstyle** Provide Sider's recommended ruleset [#1619](https://github.com/sider/runners/pull/1619)
```
Emphasize the tool name and correct the PR number.

2020-11-17 05:18 UTC, suetsuguk commented on lib/runners/processor/checkstyle.rb
> +        #original_recommended_file_path(CONFIG_FILE_NAME)
```suggestion
#      when "sider"
#        trace_writer.message "The `config` option in `#{config.path_name}` is not specified. Sider uses our recommended ruleset instead."
         #original_recommended_file_path(CONFIG_FILE_NAME)
```

Write an information message to let users know Sider uses the recommended ruleset when `config` option is not set. This is equivalent of https://github.com/sider/runners/pull/1505/files#diff-6b8d6baba827f1ad3d2b216567d33f5daa6d117154a89aa9a2084ed9032a0ccdR18
Also make the "when" line disabled until we release the ruleset.

2020-11-17 05:31 UTC, suetsuguk commented on lib/runners/recommended_config.rb
> +        After the release, Sider will automatically apply our recommended ruleset if you don't specify the #{config_key} option in your `#{config.path_name}`.
```suggestion
        After the release, Sider will automatically apply our recommended ruleset if you don't specify the `#{config_key}` option in your `#{config.path_name}`.
```

Just nitpicking.

2020-11-17 08:18 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +        #original_recommended_file_path(CONFIG_FILE_NAME)
The funciton "config_file" may be called some times. And I want to call "trace_writer" in the constructor of this class.

2020-11-17 08:18 UTC, sleeeto commented on CHANGELOG.md
> +- Checkstyle Provide Sider's recommended ruleset [#1505](https://github.com/sider/runners/pull/1619)
fixed

2020-11-17 08:18 UTC, sleeeto commented on lib/runners/recommended_config.rb
> +        After the release, Sider will automatically apply our recommended ruleset if you don't specify the #{config_key} option in your `#{config.path_name}`.
fixed.

2020-11-17 08:31 UTC, suetsuguk commented on lib/runners/processor/checkstyle.rb
> +        #original_recommended_file_path(CONFIG_FILE_NAME)
You are right. Place it in more proper function `setup` rather than constructor.

2020-11-18 05:59 UTC, suetsuguk commented on lib/runners/processor/checkstyle.rb
> +        #original_recommended_file_path(CONFIG_FILE_NAME)
```ruby
#      if config_linter[:config]
#        trace_writer.message "The `config` option in `#{config.path_name}` is specified. The Sider's recommended ruleset is ignored."
#      else
#         trace_writer.message "The `config` option in `#{config.path_name}` is not specified. Sider uses our recommended ruleset instead."
#      end

      warn_recommended_config_option_release(:config, "early in December 2020")
```

2020-11-18 08:44 UTC, suetsuguk commented on lib/runners/processor/checkstyle.rb
> +      end
```suggestion
#      if config_linter[:config]
#        trace_writer.message "The `config` option in `#{config.path_name}` is specified. The Sider's recommended ruleset is ignored."
#      else
#        trace_writer.message "The `config` option in `#{config.path_name}` is not specified. Sider uses our recommended ruleset instead."
#      end
```

Comment out this block until the recommended ruleset is released.

2020-11-18 09:03 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +      end
fixed.

2020-11-18 09:14 UTC, suetsuguk approved these changes
LGTM

2020-11-19 00:48 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +
[suggestion] Is this comment needless?

```suggestion
```

2020-11-19 00:51 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +<module name = "Checker">
[nitpick]

```suggestion
<module name="Checker">
```

2020-11-19 00:54 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +
[suggestion] It looks needless because the default is `UTF-8`.

https://checkstyle.sourceforge.io/config.html#Checker_Properties

```suggestion
```

2020-11-19 00:54 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +  <property name="severity" value="warning"/>
[question] The default is `error`. What reason is set to `warning`?

2020-11-19 00:59 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +  </module>
[suggestion] This `SuppressionFilter` looks needless... 🤔 

```suggestion
```

2020-11-19 08:39 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +
The current default set of rules is the same as "the set of Google's rules", I have copied only.
If I have generated the new default set of rules, I will replace it.

2020-11-19 08:39 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +<module name = "Checker">
↑same

2020-11-19 08:39 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +
↑same

2020-11-19 08:39 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +  <property name="severity" value="warning"/>
↑same

2020-11-19 08:39 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +  </module>
↑same

2020-11-19 09:57 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +
Why using the Google's ruleset?

2020-11-20 03:05 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +
Some reviewers are still checking a new default ruleset,
but we need to announce changing the default ruleset soon.
And early in December we will deploy the new default ruleset.

2020-11-20 03:09 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +
OK, I think we should wait to merge this PR until our new default ruleset will complete.
I don't think it is a good idea to provide the same as Google.

2020-11-20 07:28 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +
OK, I suspend this PR.

2020-11-25 09:03 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +
Now, I have updated Checkstyle default rules.

2020-11-26 02:24 UTC, suetsuguk commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +  <module name="TreeWalker">
Can you group items in categories with indicator lines, and also list items under each category in alphabetical order. That would improve readability.
You can find category names on sidebar at [list of checks](https://checkstyle.org/checks.html).

```xml
  <module name="TreeWalker">

  <!-- Checks for Annotations -->    <- indicator
    <module name="PackageAnnotation"/>

  <!-- Checks for Block Checks -->
    <module name="AvoidNestedBlocks"/> <- alphabetical order
    <module name="EmptyBlock"/>         <-|
    <module name="EmptyCatchBlock"/>    <-+
...
```

2020-11-26 02:32 UTC, suetsuguk commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +    <module name="UniqueProperties"/>
The Translation and UniqueProperties modules should be placed under `<module name="Checker">` (not under TreeWalker).

2020-11-26 02:34 UTC, suetsuguk commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +    <module name="FileLength"/>
Also, the FileLength module should be placed under the Checker module.

2020-11-26 08:40 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +    <module name="FileLength"/>
fixed.

2020-11-26 08:41 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +    <module name="UniqueProperties"/>
Fixed.

2020-11-26 08:41 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +  <module name="TreeWalker">
I have categoried them.

2020-11-27 08:42 UTC, suetsuguk commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +    <module name="IllegalTokenText"/>
Can you remove the module `IllegalTokenText` which checks if a line matches a pattern specified by user. That does not make sense for our default rules.

2020-11-27 08:48 UTC, suetsuguk commented on lib/runners/processor/checkstyle.rb
> +      warn_recommended_config_option_release(:config, "early in December 2020")
```suggestion
      warn_recommended_config_option_release(:config, "in mid December 2020")
```

Shall we postpone the release until mid December?

2020-11-27 15:34 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +    <module name="IllegalTokenText"/>
Fixed.

2020-11-27 15:34 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +      warn_recommended_config_option_release(:config, "early in December 2020")
Fixed.

2021-02-02 07:20 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +<?xml version="1.0"?>
[suggestion] Can you rename it to `sider_recommended_config.xml`?

2021-02-02 07:37 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +<?xml version="1.0"?>
In Cpplint the name of the default ruleset is sider_recommended_CPPLINT.cfg,
so I rename to sider_recommended_CHECKSTYLE.xml in Checkstyle.

2021-02-02 07:40 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +<?xml version="1.0"?>
But other config files have only lower chars (Cpplint is out of convention).
I think that using only lower chars for file names is a good habit.

2021-02-02 08:22 UTC, sleeeto commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +<?xml version="1.0"?>
OK, I renamed upper filename to lower filename.

2021-02-02 08:23 UTC, ybiquitous commented on images/checkstyle/sider_recommended_CHECKSTYLE.xml
> +<?xml version="1.0"?>
Thanks 👍

2021-02-02 08:26 UTC, ybiquitous commented on images/checkstyle/sider_recommended_checkstyle.xml
> +          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
[suggestion] How about changing DTD to the latest one?

```suggestion
<!DOCTYPE module PUBLIC
          "-//Checkstyle//DTD Checkstyle Configuration 1.3//EN"
          "https://checkstyle.org/dtds/configuration_1_3.dtd">
```

https://github.com/checkstyle/checkstyle/blob/a180c9d2f2d23c16ebad2384dcfd4493a2c28348/src/main/resources/google_checks.xml#L2-L4

2021-02-02 08:29 UTC, ybiquitous commented on images/checkstyle/sider_recommended_checkstyle.xml
> +</module>
[suggestion] Can you please set up [EditorConfig](https://editorconfig.org/) with your editor?
Perhaps, the final new line should be inserted.

https://github.com/sider/runners/blob/cc3d84c47c605ab2134348edb6d9d24d50a01218/.editorconfig#L7

2021-02-02 08:30 UTC, ybiquitous commented on lib/runners/processor/checkstyle.rb
> +      #  original_recommended_file_path(CONFIG_FILE_NAME)
[question] Why comment out?

2021-02-04 00:57 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +      #  original_recommended_file_path(CONFIG_FILE_NAME)
When recommended ruleset is released, I will comment in it. This branch announce only.

2021-02-04 00:57 UTC, sleeeto commented on images/checkstyle/sider_recommended_checkstyle.xml
> +</module>
Thanks, I installed.

2021-02-04 00:58 UTC, sleeeto commented on images/checkstyle/sider_recommended_checkstyle.xml
> +          "http://checkstyle.sourceforge.net/dtds/configuration_1_3.dtd">
fixed.

2021-02-08 06:04 UTC, sleeeto commented
@ybiquitous PRの確認お願いいたします。

2021-02-08 06:09 UTC, sleeeto commented
@ybiquitous Please check this PR.

2021-02-08 06:22 UTC, ybiquitous commented on lib/runners/processor/checkstyle.rb
> +    CONFIG_FILE_NAME = "checkstyle.xml".freeze
[suggestion] 

- I think `original_recommended_file_path` is needless because it will be hard for us to grep the file path.
- `CONFIG_FILE_NAME` seems ambiguous to me.

```suggestion
    DEFAULT_CONFIG_FILE = (Pathname(Dir.home) / "sider_recommended_checkstyle.xml").to_path.freeze
```

2021-02-08 06:22 UTC, ybiquitous commented on lib/runners/processor/checkstyle.rb
> +      #warn_recommended_config_option_release(:config, "in early March 2021")
[question] Is this comment needed still?

2021-02-08 06:24 UTC, ybiquitous commented on test/smokes/checkstyle/default_rules/sideci.yml
> +linter:
[suggestion] Please use `sider.yml` instead of `sideci.yml` when you add a new file.

2021-02-08 08:07 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +    CONFIG_FILE_NAME = "checkstyle.xml".freeze
Fixed.

2021-02-08 08:08 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +      #warn_recommended_config_option_release(:config, "in early March 2021")
Already this comment is not necessary. I removed this.

2021-02-08 08:08 UTC, sleeeto commented on test/smokes/checkstyle/default_rules/sideci.yml
> +linter:
OK, I renamed this.

2021-02-08 08:11 UTC, sleeeto commented
@ybiquitous Now, ready for merge.

2021-02-08 08:14 UTC, ybiquitous commented
@sleeeto Please push your new commits.

2021-02-08 08:49 UTC, sleeeto commented
@ybiquitous Sorry, I pushed.

2021-02-08 08:56 UTC, ybiquitous requested changes

2021-02-08 08:56 UTC, ybiquitous commented on lib/runners/processor/checkstyle.rb
> +    DEFAULT_CONFIG_FILE = (Pathname(Dir.home) / "sider_recommended_checkstyle.xml").to_path.freeze
[suggestion] Please add the constant to `checkstyle.rbs` also to fix the Steep error:

> [error] Cannot find the declaration of constant `DEFAULT_CONFIG_FILE`

https://github.com/sider/runners/blob/5c97f2c2208895c7d3fd331f85e07268ec3e3661/sig/runners/processor/checkstyle.rbs

2021-02-08 08:56 UTC, ybiquitous commented on lib/runners/recommended_config.rb
> +
[suggestion] Can you please remove the new methods in this module?

2021-02-08 10:15 UTC, sleeeto commented on lib/runners/recommended_config.rb
> +
OK, I removed this.

2021-02-08 10:16 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +    DEFAULT_CONFIG_FILE = (Pathname(Dir.home) / "sider_recommended_checkstyle.xml").to_path.freeze
I ddded DEFAULT_CONFIG_FILE in checkstyle.rbs.

2021-02-08 10:17 UTC, sleeeto commented
@ybiquitous fixed these codes.

2021-02-08 13:19 UTC, ybiquitous requested changes

2021-02-08 13:19 UTC, ybiquitous commented on lib/runners/processor/checkstyle.rb
> -
Please revert this removed line.

2021-02-08 13:19 UTC, ybiquitous commented on lib/runners/processor/checkstyle.rb
> +      file = config_linter[:config] || "google" # Change "sider" when recommended ruleset is released.
[suggestion] How about adding `TODO`?

```suggestion
      file = config_linter[:config] || "google" # TODO: Change "sider" when recommended ruleset is released.
```

2021-02-08 13:19 UTC, ybiquitous commented on lib/runners/recommended_config.rb
> +
[suggestion] This method `warn_recommended_config_option_release` also seems unused, so how about removing it?

2021-02-08 13:25 UTC, ybiquitous commented on lib/runners/processor/checkstyle.rb
> +        DEFAULT_CONFIG_FILE
[suggestion] Please address the following Steep error:

> [error] The branch is unreachable because the condition is exhaustive

1. Run `bundle rake steep:check'[true]'` on your terminal.
2. Commit changed `steep_expectations.yml`.

2021-02-09 06:24 UTC, sleeeto commented on lib/runners/recommended_config.rb
> +
That method "warn_recommended_config_file_release" is not used also, remove these methods ?

2021-02-09 06:29 UTC, ybiquitous commented on lib/runners/recommended_config.rb
> +
Yes, please.

2021-02-10 07:49 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> -
reverted.

2021-02-10 07:50 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +      file = config_linter[:config] || "google" # Change "sider" when recommended ruleset is released.
added "TODO".

2021-02-10 07:50 UTC, sleeeto commented on lib/runners/recommended_config.rb
> +
I removed these methods.

2021-02-10 07:51 UTC, sleeeto commented on lib/runners/processor/checkstyle.rb
> +        DEFAULT_CONFIG_FILE
commited changed "steep_expectations.yml"

2021-02-10 07:52 UTC, sleeeto commented
@ybiquitous ready for merge.

2021-02-10 07:53 UTC, ybiquitous commented on sig/runners/recommended_config.rbs
> -    def deploy_recommended_config_file: (String) -> void
`deploy_recommended_config_file` is still needed?

2021-02-10 09:06 UTC, sleeeto commented on sig/runners/recommended_config.rbs
> -    def deploy_recommended_config_file: (String) -> void
In CppLint, this method is still used... I think this method, this feature already are not needed.

2021-02-10 09:17 UTC, ybiquitous commented on sig/runners/recommended_config.rbs
> -    def deploy_recommended_config_file: (String) -> void
OK, if we will use the method, this deletion of `deploy_recommended_config_file` should be reverted:

https://github.com/sider/runners/pull/1619/files#diff-6b8d6baba827f1ad3d2b216567d33f5daa6d117154a89aa9a2084ed9032a0ccdR3

2021-02-15 10:54 UTC, sleeeto commented on sig/runners/recommended_config.rbs
> -    def deploy_recommended_config_file: (String) -> void
I will remove this method at another PR.

2021-02-16 07:08 UTC, sleeeto commented
@ybiquitous Ready for merge.

2021-02-17 00:39 UTC, ybiquitous requested changes

2021-02-17 00:39 UTC, ybiquitous commented on CHANGELOG.md
> +- **Slim-Lint** New support [#2014](https://github.com/sider/runners/pull/2014)
Please fix the changelog according to `master`.

2021-02-17 00:39 UTC, ybiquitous commented on sig/runners/recommended_config.rbs
> -    def deploy_recommended_config_file: (String) -> void
Please revert the deletion of `def deploy_recommended_config_file: (String) -> void` because `deploy_recommended_config_file` is not removed yet in this PR.

2021-02-17 00:39 UTC, ybiquitous commented on steep_expectations.yml
> +    code: Ruby::NoMethod
This error is caused by the deletion of `deploy_recommended_config_file` in `sig/runners/recommended_config.rbs`.

2021-02-17 02:19 UTC, sleeeto commented on CHANGELOG.md
> +- **Slim-Lint** New support [#2014](https://github.com/sider/runners/pull/2014)
fixed.

2021-02-17 02:20 UTC, sleeeto commented on steep_expectations.yml
> +    code: Ruby::NoMethod
I updated a steep file and run steep.

2021-02-17 02:20 UTC, sleeeto commented
@ybiquitous fixed.

2021-02-17 02:25 UTC, ybiquitous commented on CHANGELOG.md
> +- **Slim-Lint** New support [#2014](https://github.com/sider/runners/pull/2014)
Is this addition needless?

```suggestion
```

2021-02-17 04:46 UTC, sleeeto commented on CHANGELOG.md
> +- **Slim-Lint** New support [#2014](https://github.com/sider/runners/pull/2014)
I missed and fixed.

2021-02-17 04:48 UTC, sleeeto commented
@ybiquitous Ready.

2021-02-17 04:59 UTC, ybiquitous approved these changes
OK, LGTM 👍

2021-02-17 04:59 UTC, merged