[flake8] Provide Sider's recommended set of rules
sider/runners pull request #1980
Opened 2021-01-28 06:06 UTC by sleeeto

> Check the following items.

- [] Add a new [changelog](https://github.com/sider/runners/blob/master/CHANGELOG.md) entry if this change is notable.

If you are adding a new runner:

- [] ~~Read and follow the [document](https://github.com/sider/runners/blob/master/docs/how-to-write-a-new-runner.md) for a new runner.~~
- [] ~~Add a new tool to [`analyzers.yml`](https://github.com/sider/runners/blob/master/analyzers.yml).~~
- [] ~~Run `bundle exec rake readme:generate` and commit the updated `README.md`.~~
- [] ~~Add a new tool to the [Dependabot configuration](https://github.com/sider/runners/blob/master/.github/dependabot.yml) if needed.~~
- [] ~~Provide option(s) that users can customize.~~
- [] Write smoke test cases. E.g. all options, successful end, warnings, errors, etc.
- [] ~~Add a [CI setting](https://github.com/sider/runners/blob/master/.github/workflows/build.yml).~~
- [] Write a [document](https://github.com/sider/sider-docs) and link the pull request -> sider/sider-docs#506

2021-01-29 01:09 UTC, suetsuguk commented on images/flake8/Dockerfile.erb
> +#COPY --chown=<%= chown %> images/flake8/sider_recommended_config.ini ${RUNNER_USER_HOME}/.config/flake8 # おすすめルールを適用後
Remove this line.

2021-01-29 01:32 UTC, suetsuguk commented on lib/runners/recommended_config.rb
> -      return if exists_in_repository?(config_filename)
- Add `add_warning` around [here](https://github.com/sider/runners/blob/b8a910dabad33cd6cb06a755a1785f854e33efea/lib/runners/processor/flake8.rb#L66-L67).
- In the warning message, refer to both existing images/flake8/sider_config.ini and new coming images/flake8/sider_recommended_config.ini
- And, revert changes for recommended_confing.rb. We will not use this class this time.

2021-01-29 01:44 UTC, suetsuguk commented on images/flake8/sider_recommended_config.ini
> +ignore = E121, E126, E127, E128, E203, E226, E231, E241, E251, E261, E265, E302, E303, E305, E402, E501, W291, W292, W293, W391, W504, F403, B007, B950
- Align the rule IDs vertically.
- Add E741 and W503

2021-02-01 06:46 UTC, suetsuguk commented on images/flake8/sider_recommended_config.ini
> +    E203,
Add E225

2021-02-01 06:56 UTC, suetsuguk commented on lib/runners/processor/flake8.rb
> +        Sider's recommended configuration file is about to be released in early Mar 2021.
typo

```suggestion
        Sider's recommended configuration file is about to be released in early March 2021.
```

2021-02-01 07:26 UTC, suetsuguk commented on lib/runners/processor/flake8.rb
> +        After) https://github.com/sider/runners/blob/master/images/flake8/sider_recommended_config.ini
Since we already have a recommended configuration file for flake8, the message should be like as follows to notify users to check the difference. Also, we can use the link notation of Markdown.

--
Sider's recommended configuration file is about to be updated in early March 2021.
New configuration [file](https://github.com/sider/runners/blob/master/images/flake8/sider_recommended_config.ini) has more strict rules than the current configuration [file](https://github.com/sider/runners/blob/master/images/flake8/sider_config.ini) and may give you more useful issues.
If you want to keep using the current configuration file, you need to save a copy of the [file](https://github.com/sider/runners/blob/master/images/flake8/sider_config.ini) with a file name `.flake8` in your repository.
--

2021-02-01 07:35 UTC, suetsuguk commented on test/smokes/flake8/expectations.rb
> +  issues: [], analyzer: { name: "Flake8", version: default_version }
Please insert new-line between issues and analyzer.

```suggestion
  issues: [],
  analyzer: { name: "Flake8", version: default_version }
```

2021-02-01 08:05 UTC, sleeeto commented on images/flake8/sider_recommended_config.ini
> +    E203,
Done.

2021-02-01 08:27 UTC, sleeeto commented on lib/runners/processor/flake8.rb
> +        Sider's recommended configuration file is about to be released in early Mar 2021.
Done.

2021-02-01 08:28 UTC, sleeeto commented on lib/runners/processor/flake8.rb
> +        After) https://github.com/sider/runners/blob/master/images/flake8/sider_recommended_config.ini
Thanks.

2021-02-01 08:28 UTC, sleeeto commented on test/smokes/flake8/expectations.rb
> +  issues: [], analyzer: { name: "Flake8", version: default_version }
Done.

2021-02-01 10:10 UTC, suetsuguk commented on CHANGELOG.md
> +- **Flake8** Provide Sider's recommended ruleset [#1980](https://github.com/sider/runners/pull/1980)
Move this line under `Misc:`.

2021-02-02 00:28 UTC, sleeeto commented on CHANGELOG.md
> +- **Flake8** Provide Sider's recommended ruleset [#1980](https://github.com/sider/runners/pull/1980)
Done.

2021-02-08 06:04 UTC, sleeeto commented
PRの確認お願いいたします。

2021-02-08 06:09 UTC, sleeeto commented
@ybiquitous Please check this PR.

2021-02-08 06:19 UTC, ybiquitous approved these changes

2021-02-17 05:21 UTC, ybiquitous requested changes
@sleeeto Please update the changelog.

2021-02-17 07:10 UTC, ybiquitous approved these changes
LGTM 👍

2021-02-17 08:23 UTC, suetsuguk approved these changes
LGTM

2021-02-19 01:16 UTC, merged