[ESLint] Provide Sider's recommended set of rules
sider/runners pull request #2165
Opened 2021-03-11 07:54 UTC by sleeeto

> Explain a summary, purpose, or background for this change.

We provide Sider's recommended ruleset for ESLint.

> Refer related issues or pull requests (e.g. `Close #123` or `None`).

None.

> Check the following if needed.

- [] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

2021-03-11 08:16 UTC, sleeeto commented
@yykamei I checked some rules which do not seem important like '# USELESS'
Please check them.

2021-03-12 00:36 UTC, ybiquitous commented on images/eslint/sider_recommended_eslint.yml
> +  symbol-description: [error]
[suggestion] How about sorting the rules alphabetically?

2021-03-12 00:36 UTC, ybiquitous commented on images/eslint/sider_recommended_eslint.yml
> +root: true
[question] Is not `extends: "eslint:recommended"` necessary?

2021-03-12 01:56 UTC, yykamei reviewed
I agree with https://github.com/sider/runners/pull/2165#discussion_r592828963.
I think it's good to reduce the list of rules in `.eslintrc` in terms of maintaining. Or, are there any difficulties to use `extends: 'eslint:recommended'`?

2021-03-16 11:40 UTC, sleeeto commented
@ybiquitous @yykamei 
How about this updated recommended ruleset ?
- add 'extends: eslint:recommended'
- add enabled/disabled rules from eslint:recommended rules.
- add 'category' for each rules.

2021-03-16 23:47 UTC, ybiquitous commented on images/eslint/sider_recommended_eslint.yml
> +  no-await-in-loop: [error]
[question] What reason for using `[error]` instead of `error`?
`error` seems better, considering consistency with `off`.

```suggestion
  no-await-in-loop: error
```

2021-03-17 02:28 UTC, sleeeto commented on images/eslint/sider_recommended_eslint.yml
> +  no-await-in-loop: [error]
OK, I fixed it.

2021-03-17 02:47 UTC, sleeeto commented
@ybiquitous @yykamei Ready.

2021-03-17 02:51 UTC, ybiquitous requested changes
Please merge `master` branch and update CHANGELOG.md again.

2021-03-17 03:18 UTC, yykamei reviewed
Thank you. I understood each rule is categorized based on [Rules](https://eslint.org/docs/rules/). It makes sense, but I'd like to know what rules are overridden. I guess [this](https://github.com/sider/runners/pull/2165/files#diff-b191f3ba22ea3876e419174f909919117eb50e53c6069544f9e0612e5aaa9f23R13) section indicates them, but it's better to explain explicitly.

2021-03-17 06:31 UTC, ybiquitous commented
[IMO] The descriptions are added via 2cfbfcb, but it seems enough to me to just add a link to <https://eslint.org/docs/rules/>.

2021-03-17 08:45 UTC, sleeeto commented
@ybiquitous @yykamei Ready.

2021-03-17 08:56 UTC, ybiquitous approved these changes
LGTM 👍

2021-03-18 01:06 UTC, yykamei commented
> I'd like to know what rules are overridden.

How about this? From the latest `images/eslint/sider_recommended_eslint.yml`, it would be a bit hard to know what rules are overridden from `eslint:recommended`. I think almost all rules are not included in `eslint:recommended`.

2021-03-18 07:51 UTC, yykamei commented on images/eslint/sider_recommended_eslint.yml
> +  # Disabled [Variables]
How about this?

```suggestion
  # Disabled [Variables] (Overriding rules included in `eslint:recommended`)
```

2021-03-18 08:27 UTC, yykamei approved these changes
LGTM

2021-03-18 08:42 UTC, sleeeto commented
@yykamei @ybiquitous Ready to merge.

2021-03-18 08:52 UTC, merged