[RuboCop] Enable Sider's recommended set of rules
sider/runners pull request #2323
Opened 2021-04-23 10:30 UTC by sleeeto

> Explain a summary, purpose, or background for this change.

Enable Sider's recommended set of rules.

> Refer related issues or pull requests (e.g. `Close #123` or `None`).

None.

> Check the following if needed.

- [ ] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

2021-04-26 01:53 UTC, suetsuguk reviewed
Please be sure to add a note to CHANGELOG.

2021-04-26 01:56 UTC, suetsuguk commented on test/smokes/rubocop/expectations.rb
> -      message: "Line is too long. [218/200]",
Can you update a test file so that the older version of RuboCop reports an issue, e.g. Lint/NumberConversion?

2021-04-26 01:56 UTC, suetsuguk commented on test/smokes/rubocop/expectations.rb
> -      message: "Line is too long. [218/200]",
Same as above.

2021-04-26 01:56 UTC, suetsuguk commented on test/smokes/rubocop/expectations.rb
> -      message: "Line is too long. [218/200]",
Same as above.

2021-04-26 05:30 UTC, sleeeto commented on test/smokes/rubocop/expectations.rb
> -      message: "Line is too long. [218/200]",
I added a error code of Lint/NumberConversion in a test. Is this OK ?

2021-04-26 05:45 UTC, suetsuguk commented on test/smokes/rubocop/expectations.rb
> -      message: "Line is too long. [218/200]",
That's OK.

2021-04-26 05:48 UTC, suetsuguk commented on CHANGELOG.md
[nitpick] remove this empty line.

2021-04-26 06:41 UTC, sleeeto commented
@suetsuguk 
I fixed them.
And I want to merge this branch after this week (2021/04/26-4/30) release.

2021-04-26 07:00 UTC, suetsuguk commented on test/smokes/rubocop/expectations.rb
> +  analyzer: { name: "RuboCop", version: "0.71.0" },
[nitpick] move this line to the original position (just above the `warnings` line).

2021-04-26 07:02 UTC, suetsuguk commented on test/smokes/rubocop/expectations.rb
> +  analyzer: { name: "RuboCop", version: "0.72.0" },
[nitpick] move this line to the original position (just above the warnings line).

2021-04-26 07:50 UTC, sleeeto commented on test/smokes/rubocop/expectations.rb
> -      message: "Line is too long. [218/200]",
Fixed

2021-04-26 07:51 UTC, sleeeto commented on test/smokes/rubocop/expectations.rb
> -      message: "Line is too long. [218/200]",
Fixed.

2021-04-26 07:51 UTC, sleeeto commented on CHANGELOG.md
Fixed.

2021-04-26 08:10 UTC, sleeeto commented on test/smokes/rubocop/expectations.rb
> +  analyzer: { name: "RuboCop", version: "0.71.0" },
Fixed.

2021-04-26 08:25 UTC, sleeeto commented on test/smokes/rubocop/expectations.rb
> +  analyzer: { name: "RuboCop", version: "0.72.0" },
Fixed.

2021-04-26 08:26 UTC, suetsuguk approved these changes
LGTM.

2021-04-26 08:34 UTC, sleeeto commented
@ybiquitous 
I have a question.
Why this error always appears in haml_lint. I have not updated haml_lint.
"#<Errno::ENOENT: No such file or directory @ rb_sysopen - /home/analyzer_runner/sider_recommended_rubocop.yml>"

2021-04-26 12:18 UTC, ybiquitous commented
@sleeeto HAML-Lint and Slim-Lint internally execute RuboCop, so it is assumed to have the same config file name for RuboCop.

See also:

https://github.com/sider/runners/blob/961aac0642588d8d161a03acf62e0c6076a25c2b/lib/runners/rubocop_utils.rb#L71

https://github.com/sider/runners/blob/961aac0642588d8d161a03acf62e0c6076a25c2b/images/haml_lint/default_rubocop.yml

https://github.com/sider/runners/blob/961aac0642588d8d161a03acf62e0c6076a25c2b/images/slim_lint/default_rubocop.yml

2021-04-27 05:04 UTC, sleeeto commented
@ybiquitous How about this change ?

2021-04-27 05:16 UTC, ybiquitous commented
Can we use the new config also for HAML-Lint and Slim-Lint as below?

```diff
diff --git a/images/haml_lint/Dockerfile.erb b/images/haml_lint/Dockerfile.erb
index 655e21aa..daf6d8fa 100644
--- a/images/haml_lint/Dockerfile.erb
+++ b/images/haml_lint/Dockerfile.erb
@@ -1,5 +1,6 @@
 <%= render_erb 'images/Dockerfile.ruby.erb' %>
 
 COPY --chown=<%= chown %> images/<%= analyzer %>/*.yml ${RUNNER_USER_HOME}/
+COPY --chown=<%= chown %> images/rubocop/sider_recommended_rubocop.yml ${RUNNER_USER_HOME}/
 
 <%= render_erb 'images/Dockerfile.end.erb' %>
```

2021-04-27 09:06 UTC, sleeeto commented
@ybiquitous OK, I changed it.

2021-04-27 09:11 UTC, ybiquitous approved these changes
👍🏼

2021-04-27 09:51 UTC, ybiquitous commented
#2337 should fix the test failure.

2021-05-17 01:09 UTC, sleeeto commented
@ybiquitous Ready.

2021-05-17 01:54 UTC, ybiquitous requested changes

2021-05-17 01:54 UTC, ybiquitous commented on CHANGELOG.md
> +- **RuboCop** Enable new recommended configuration [#2323](https://github.com/sider/runners/pull/2323)
Incorrect position.

2021-05-17 04:41 UTC, sleeeto commented on CHANGELOG.md
> +- **RuboCop** Enable new recommended configuration [#2323](https://github.com/sider/runners/pull/2323)
OK, fixed.

2021-05-17 08:46 UTC, ybiquitous commented on test/smokes/rubocop/expectations.rb
> +      ],
[suggestion] Can you minimize the diff?

```suggestion
      links: %w[https://docs.rubocop.org/rubocop/cops_lint.html#lintshadowingouterlocalvariable],
```

2021-05-17 09:10 UTC, sleeeto commented on test/smokes/rubocop/expectations.rb
> +      ],
OK, upadted links.

2021-05-17 09:12 UTC, ybiquitous approved these changes
Thank you. Looks good to me. 👍🏼

2021-05-17 09:26 UTC, merged