[PMD Java] Enable Sider's recommended set of rules
sider/runners pull request #2345
Opened 2021-04-28 10:06 UTC by sleeeto

> Explain a summary, purpose, or background for this change.

Enable Sider's recommended set of rules.

> Refer related issues or pull requests (e.g. `Close #123` or `None`).

None.

> Check the following if needed.

- [ ] Add a new entry to [CHANGELOG.md](https://github.com/sider/runners/blob/master/CHANGELOG.md) if this change is notable.

2021-04-30 02:49 UTC, suetsuguk commented on test/smokes/pmd_java/expectations.rb
> +      links: %W[https://pmd.github.io/pmd-6.33.0/pmd_rules_java_errorprone.html#avoidcallingfinalize],
```suggestion
      links: %W[https://pmd.github.io/pmd-#{default_version}/pmd_rules_java_errorprone.html#avoidcallingfinalize],
```

Revert the code, then this test will pass.

2021-04-30 02:49 UTC, suetsuguk commented on test/smokes/pmd_java/expectations.rb
> +      links: %W[https://pmd.github.io/pmd-6.33.0/pmd_rules_java_design.html#donotextendjavalangerror],
Same as above.

2021-05-17 01:34 UTC, sleeeto commented on test/smokes/pmd_java/expectations.rb
> +      links: %W[https://pmd.github.io/pmd-6.33.0/pmd_rules_java_errorprone.html#avoidcallingfinalize],
OK, ready.

2021-05-17 01:34 UTC, sleeeto commented on test/smokes/pmd_java/expectations.rb
> +      links: %W[https://pmd.github.io/pmd-6.33.0/pmd_rules_java_design.html#donotextendjavalangerror],
OK, fixed.

2021-05-17 01:35 UTC, sleeeto commented on test/smokes/pmd_java/expectations.rb
> +      links: %W[https://pmd.github.io/pmd-6.33.0/pmd_rules_java_security.html#hardcodedcryptokey],
OK, fixed.

2021-05-17 04:45 UTC, sleeeto commented
@ybiquitous Ready.

2021-05-17 09:21 UTC, suetsuguk approved these changes
I have verified your changes. Thank you.

2021-05-17 09:28 UTC, ybiquitous requested changes
@sleeeto Can you resolve the conflict, please?

2021-05-17 09:36 UTC, sleeeto commented
@ybiquitous OK, resolved.

2021-05-17 09:36 UTC, ybiquitous approved these changes
Thank you 👍🏼

2021-05-17 09:38 UTC, merged