add a sider scan for GitHub action.
sider/runners pull request #2813
Opened 2021-11-17 05:59 UTC by sleeeto

### Summary or Background

add a sider scan for GitHub action.

### Issues or Pull Requests

https://github.com/sider/runners/issues/2812

### Checklist

No change logs.

2021-11-17 07:06 UTC, radomirbosak commented on .github/workflows/sider_scan.yml
> +        run: |
> __[actionlint]__ shellcheck reported issue in this script: SC2215:warning:5:1: This flag is used as a command name. Bad line break or missing [ .. ]? ([view](https://sider.review/gh/repos/202486306/pulls/2813#issue-6278071))
>
> <details>
>
> | Rule |
> | ---- |
> | `shellcheck/SC2215` |
>
> References:
> - <https://github.com/koalaman/shellcheck/wiki/SC2215>
>
> You can [close this issue](https://sider.review/gh/repos/202486306/pulls/2813#issue-6278071) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

Missing backslash after
```
-f /tmp/output.radump
```

2021-11-17 07:07 UTC, radomirbosak requested changes
actionlint reports errors

2021-11-17 09:03 UTC, sleeeto commented on .github/workflows/sider_scan.yml
> +        run: |
Thanks, I fixed it.

2021-11-17 16:48 UTC, gnakagaw commented
I've fixed all `actionlint` warnings.

2021-11-17 16:53 UTC, merged

2021-11-18 00:25 UTC, radomirbosak commented on .github/workflows/sider_scan.yml
> +name: Sidr Scan Runner
```suggestion
name: Sider Scan Runner
```

2021-11-18 00:34 UTC, radomirbosak commented on .github/workflows/sider_scan.yml
> +          }" > .siderscan.json
I wonder if we can use something like bash heredoc here to avoid the backslashes (at the end of line and before double quotes).

e.g.
```bash
cat << EOF > file.txt
The current working directory is: $PWD
You are logged in as: $(whoami)
EOF
```

I haven't yet tried if this works in github actions workflow file too.

2021-11-18 02:44 UTC, gnakagaw commented on .github/workflows/sider_scan.yml
> +          }" > .siderscan.json
I found an example using heredoc in `run` command.
https://qiita.com/hkusu/items/3dbf09f7fa83ba6d457c#%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%97%E3%83%88

BTW, IMO, we should use [`envsubst`](https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html) to inject secrets into the config file.

2021-11-18 02:44 UTC, gnakagaw commented on .github/workflows/sider_scan.yml
> +name: Sidr Scan Runner
Thanks. I'll fix that.

2021-11-18 03:06 UTC, radomirbosak commented on .github/workflows/sider_scan.yml
> +          }" > .siderscan.json
Just in case, I looked at the log produced by the action, but all secrets have been fortunately replaces by `***`.

2021-11-18 03:08 UTC, gnakagaw commented on .github/workflows/sider_scan.yml
> +          }" > .siderscan.json
>  all secrets have been fortunately replaces by ***
I've tested it of course 😄

2021-11-18 03:09 UTC, gnakagaw commented
I'm attacking the issue in #2815.